package com.sportsbook.admin.audit;

public enum AdminAction {
  WALLET_REFUND,
  RISK_LIMIT_UPDATE,
  RISK_LIMIT_CLEAR,
  MARKET_SUSPEND,
  MARKET_CLOSE,
  MARKET_REOPEN,
  RESULT_CANDIDATE_APPROVE,
  RESULT_CANDIDATE_REJECT,
  SETTLEMENT_REVISION_RETRY
}
